[package]
name = "cursormochi-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
cursormochi-core.workspace = true
cursormochi-app.workspace = true
cursormochi-platform.workspace = true
gtk.workspace = true
gio.workspace = true
glib.workspace = true
[[bin]]
name = "cursor-mochi"
path = "src/main.rs"
